spring.application.name=springboot-web
spring.datasource.url=jdbc:mysql://localhost:3306/ufinet_autos?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.thymeleaf.check-template-location=false

jwt.secret-key=a8fcbf07f64b15516175f8b712b3f18af81d7aad41409f2c584cb215b93c30f1
jwt.expiration=86400000
jwt.refresh-token=

